name: Build and Maybe Deploy Docs

on:
  push:
  merge_group:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      REACT_APP_DOC_SEARCH_APP_ID: ${{ secrets.DOC_SEARCH_APP_ID }}
      REACT_APP_DOC_SEARCH_INDEX_NAME: ${{ secrets.DOC_SEARCH_INDEX_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true
          install: false # don't run install, as we want to install with --frozen-lockfile below
          # don't specify the pnpm version here, as we'll use the version from the devEngines field in package.json
          # this also specifies the version of node to use, so we don't need to install that separately

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

        # run all checks, including audit
      - run: pnpm run check

      - name: Build website
        run: pnpm run build

      - name: Deploy to GitHub Pages if Main
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: brave-builds[bot]
          user_email: brave-builds@brave.com
